version: '3.7'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "3306:5432"
    networks:
      - backend
    volumes: 
      - dbdata:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  dbdata: